trigger:
  branches:
    include:
      - master

  paths:
    include:
      - '*'

variables:
  buildConfiguration: 'Release'
  acrHostName: 'crmassmotion.azurecr.io'
  acrName: 'crmassmotion'
  scName: 'arup-massmotion-dev-rg'
  imageName: 'csmmcocreate'

stages:

# Build Stage
- stage: Build
  jobs:
  - job: BuildImage
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        containerRegistry: '$(acrName)'
        repository: '$(imageName)'
        imageName: '$(imageName):$(Build.BuildId)'
        command: 'build'
        dockerFile: Dockerfile

    - task: Docker@2
      displayName: 'Push Docker Image'
      inputs:
        containerRegistry: '$(acrName)'
        repository: '$(imageName)'
        imageName: '$(imageName):$(Build.BuildId)'
        command: 'push'